version: '{build}'
os: Visual Studio 2017
configuration: Debug
branches:
  only:
    - master
build_script:
- ps: >-
    ./build.ps1
test_script:
- ps: ./cover.ps1
artifacts:
  - path: '**\*.nupkg'
    name: NuGet Packages